- The number of images per product is limited (from 1 to 5)
sakurassweets/sakurassweets-backend pull request #33
Opened 2024-06-28 00:38 UTC by sh0TGuN500

- Pagination page size changed from 9 to 12
- Renamed 'product_rating' to 'product_review'
- Added automation for product images and product publishing
- Deleting image files when deleting a record from the database (and when updating an image)

Implement:

- Automation for product images:
  - First image is main_image
  - Next image with main_image = True is mani image
  - If the main image is deleted, another image becomes the main image if it exists, otherwise the product is not published
- Product publishing:
  - A product don't become published if its main image is not defined

This is a:

- [x] 🍕 Feature
- [x] 🧑‍💻 Code Refactor
- [x] Other

2024-06-28 06:21 UTC, sukui24 requested changes
Request changes, left the comments

2024-06-28 06:21 UTC, sukui24 commented on core/product/models.py
> +        # self.validate_related_objects()
Якщо закоментований код може бути потрібним в майбутньому - Напиши комент чому. В іншому випадку видали його.

2024-06-28 06:21 UTC, sukui24 commented on core/image/views.py
> +        if related_to_id:
Можна використати:
```python
if related_to_id := request.data.get('related_to')
```
Але звісно ж по бажанню.

2024-06-28 06:21 UTC, sukui24 commented on core/product/signals.py
> +            next_image.save()
Логіка трохи дивно написана. По перше не думаю що тут потрібно перевіряти чи інстанс паблішед, судячи з назви. Але якщо це потрібно і немає іншого способу валідувати, то окей.

Також тобі варто користуватись `return'ами`, це робить код більш читабельним. Я б переписав його так:
```python
    if not instance.is_published:
        return false

    product_images = instance.image_set.all()
    has_images = product_images.exists()
    has_main_image = product_images.filter(main_image=True).exists()

    if not has_images:
        instance.is_published = False
        instance.save(update_fields=['is_published'])
        return false # or true, depends on what this code means (fail or success)

    # Враховуючи що далі немає ніякого коду - розглянь моживість просто забрати цю перевірку з if, але якщо це не можливо то окей
    if has_images and not has_main_image:
        next_image = product_images.first()
        next_image.main_image = True
        next_image.save()

2024-06-30 15:49 UTC, sh0TGuN500 commented on core/product/signals.py
> +            next_image.save()
Функція тільки змінює інстанс в залежності від параметрів інстансу і більше від неї нічого не потрібно. Вона спрацьовує при кожному збереженні/оновленні екземпляру моделі Product

2024-06-30 15:54 UTC, sh0TGuN500 commented on core/image/views.py
> +        if related_to_id:
Створив змінну тому що в 30-му рядку вона використовується вдруге

2024-06-30 15:56 UTC, sh0TGuN500 reviewed
Прошу переглянути =)

2024-06-30 15:57 UTC, sh0TGuN500 commented on core/product/models.py
> +        # self.validate_related_objects()
Ok

2024-07-02 06:09 UTC, sukui24 approved these changes

2024-07-04 22:11 UTC, merged